export {default as mpage} from '../../assets/projects/mpage/index.png'
export {default as slist} from '../../assets/projects/slist/index.jpg'
export {default as ppage} from '../../assets/projects/ppage/index.png'
export {default as blist} from '../../assets/projects/pban/index.png'
export {default as pprofile} from '../../assets/projects/pprofile/index.png'
export {default as pmatches} from '../../assets/projects/pmatches/index.png'